### ISSUE TITLE
pybsdp service

### ISSUE THREAD

**Issue by ghost** [cabal95/pybsdp#1]
I have tried everything and can not get the pybsdp service to start
Next edit the config file at /etc/pybsdp.conf and update the paths and username/password to match your configuration. Finally we need to start the pybsdp service (it is set to run at boot, but it has not been started yet).

sudo service pybsdp start

**Comment by cabal95** [comment]
Can you give more information on exactly what step failed and what error message you are getting?  I am assuming it failed on the "sudo service pybsdp start" command you mentioned, but what is the actual output from the command?

**Comment by ghost** [comment]
I did every step on this site, http://www.blueboxmoon.com/wordpress/?p=929 and after editing the /etc/pybsdp.conf file is says to start the pybsdp service and I get no such directory or file. here is a screenshot https://www.dropbox.com/s/5ieqqwc6eud4dfg/Screenshot%202015-10-10%2017.48.04.png?dl=0

**Comment by cabal95** [comment]
Can you copy and paste the exact command run and the response?  "no such file or directory" doesn't sound like the right response from the "service" command, if it runs into an error like that it should say something more like "pybsdp: unrecognized service".

Also include the output from 'ls -l /etc/pybsdp.conf' to verify that the config file is in the right place.

**Comment by ghost** [comment]
Here you go, https://www.dropbox.com/s/v09cptzaw5xgfrk/Screenshot%202015-10-10%2018.01.45.png?dl=0

**Comment by cabal95** [comment]
Hm.  Okay, couple more questions:
1) Which version of Ubuntu are you using? Wonder if it is a newer version and they changed something in the way 'service' operates.
2) Can you check 'ls -l /etc/init/pybsdp.conf'
3) Assuming the above shows a file, also 'cat /etc/init/pybsdp.conf'

**Comment by cabal95** [comment]
You may be running into the same problem as documented here with Ubuntu 15 (assuming that is what you are running): http://www.wowza.com/forums/showthread.php?43080-Ubuntu-15-04-install-Service-fails-to-start-with-vague-error-message

Try installing the upstart-sysv package and see if that lets you start pybsdp normally. It looks like i'll have to convert the startup script to use systemd instead of upstart at some point.

**Comment by ghost** [comment]
I installed the upstart-sysv still same message

**Comment by ghost** [comment]
rebooted and seems to have the service running now
https://www.dropbox.com/s/origb13zxdbpluu/Screenshot%202015-10-11%2011.27.59.png?dl=0

**Comment by cabal95** [comment]
Great! glad that worked. I will try to make a note about needing that extra package in Ubuntu 15 for now.
